from tkinter import *
master=Tk()
v=IntVar
master.geometry("1000x500")
master.coe1=Label (master,text="phonenumber:",font=("verdana",10,"bold"),bg="#00FFFF")
master.configure(bg='#4db4f0')
f = Frame(master, padx=10, pady=10)
ff = Frame(master)
f.configure(bg="#f2c496")
def submit1():
    master.destroy()
    fourth= Tk()
    print("create")
    fourth.mainloop()

def submit2():
    master.destroy()
    fifth= Tk()
    print("read")
    fifth.mainloop()
def submit3():
    master.destroy()
    sixth= Tk()
    print("update")
    sixth.mainloop()
def submit4():
    master.destroy()
    seven= Tk()
    print("delete")
    seven.mainloop()
x=Label(master,text="DOCUMENTS",font=("verdana",10,"bold"),bg="#00FFFF")
a1=Label(master,text="create table:",font=("verdana",10,"bold"),bg="#00FFFF")
i1=Button(master,text="documentation",command=submit1)
b1=Label (master,text="read table",font=("verdana",10,"bold"),bg="#00FFFF")
i2=Button(master,text="documentation",command=submit2)
c1=Label (master,text="update table",font=("verdana",10,"bold"),bg="#00FFFF")
i3=Button(master,text="documentation",command=submit3)
d1=Label (master,text="delete table:",font=("verdana",10,"bold"),bg="#00FFFF")
i4=Button(master,text="documentation",command=submit4)
x.grid(row=1,column=4)
a1.grid(row=2,column=3)
i1.grid(row=2,column=4)
b1.grid(row=3,column=3)
i2.grid(row=3,column=4)
c1.grid(row=4,column=3)
i3.grid(row=4,column=4)
d1.grid(row=5,column=3)
i4.grid(row=5,column=4)
mainloop()